# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 865ab05f0bb370927077d703c286c428f0f20cb62790cea881132b9b26aaf76e4cae6d37f3011286ec619b728296e8972600d0e4ac45d7303ff479dd667328eb

test:
  secret_key_base: 61bca0395508dcaf24a1eb191cc4ee3e4d6ba6d13644ebee607c7c9d1fd065454eb89b8a48c18c18d71e7f02c3d3c72d0e5e502ae507bf045c72cd50625aa23e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
